pipeline {
	agent { 
		label 'java' 
	}
	
	tools {
		gradle 'gradle4.10.2'
	}
	
	stages {
		stage("build") {
			steps {
				sh 'echo Building with gradle'
				sh 'gradle -b automation_framework/build.gradle test check build'
			}
			post {
				always {
					sh 'touch automation_framework/build/test-results/test/*.xml'
					junit allowEmptyResults: true, testResults: '**/build/test-results/test/*.xml'
				}
			}
		}
		stage("Post-build") {
			steps {
				sh 'touch automation_framework/build/test-results/test/*.xml'
				junit allowEmptyResults: true, testResults: '**/build/test-results/test/*.xml'
				findbugs canComputeNew: false, defaultEncoding: '', excludePattern: '', healthy: '', includePattern: '', pattern: '**/build/reports/findbugs/*.xml', unHealthy: ''
				jacoco sourceExclusionPattern: '*/test/**'
				archiveArtifacts artifacts: '**/*.jar', excludes: '**/jacocoagent.jar', onlyIfSuccessful: true
			}
			post {
				always {
					cleanWs()
				}
			}
		}
	}
}