pipeline {
	agent { label 'java' }
	stages {
		stage("build") {
			steps {
				sh 'echo Building with gradle'
				sh '/opt/gradle/latest/bin/gradle -b automation_framework/build.gradle test check build'
			}
		}
	}
}