pipeline {
	agent { label 'java' }
	stages {
		stage("build") {
			steps {
				sh 'echo Building with gradle'
				sh '/opt/gradle/latest/bin/gradle -b automation_framework/build.gradle test check build'
			}
		}
		stage("Post-build") {
			steps {
				sh 'touch automation_framework/build/test-results/test/*.xml'
				junit allowEmptyResults: true, testResults: '**/build/test-results/test/*.xml'
				cleanWs()
			}
		}
	}
}